# Homebrew cask for https://github.com/googolmo/imprint
# Generated by .github/scripts/prepare-homebrew-cask.py
cask "imprint" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.3"
  sha256 arm:   "763a4864afaa2bb57e579503581d29583b98c8a565b7be689d0e439c573a1822",
         intel: "800ebf21d485a8c4f6594a3cf2389f530847bb73826a143d98c6481ab1728ac3"

  url "https://github.com/googolmo/imprint/releases/download/v#{version}/Imprint_#{version}_#{arch}.dmg"
  name "Imprint"
  desc "Flash OS images onto USB drives and SD cards"
  homepage "https://github.com/googolmo/imprint"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates true

  app "Imprint.app"
  binary "#{appdir}/Imprint.app/Contents/MacOS/imprint-cli", target: "imprint-cli"

  uninstall quit: "imprint.cdxtheme.com"

  zap trash: [
    "~/Library/Application Support/imprint",
    "~/Library/Caches/imprint.cdxtheme.com",
    "~/Library/Logs/imprint.cdxtheme.com",
    "~/Library/Preferences/imprint.cdxtheme.com.plist",
    "~/Library/Saved Application State/imprint.cdxtheme.com.savedState",
  ]
end
